INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('João Antonio', 2500.00, 5, 0);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Maria Santos', 2999.99, 4.5, 1);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Daniel Ferraz', 1500.50, 15, 0);
